name: golidity pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: build
        key: ${{ runner.os }}-${{ hashFiles('build') }}
    - name: Build
      run: mkdir build && cd build && cmake .. && make
