name: ylem pipeline
on: push
env:
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6
jobs:
  build:
    strategy:
      matrix:
        platform: [
          {os: ubuntu-latest, path: linux-x86_64},
	  {os: raspbian-private, path: linux-arm64},
        ]
    runs-on: ${{matrix.platform.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: sh scripts/install_deps.sh
    - name: Ccache
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ matrix.platform }}-cache-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          ${{ matrix.platform }}-cache-
    - name: Build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache ..
        make -j4 ylem
  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
        tag: ${{steps.version_bump.outputs.tag}}
        url: ${{steps.create_release.outputs.upload_url}}
    needs: build
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{secrets.GITHUB_TOKEN}}
    - name: Version
      id: version_bump
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
        WITH_V: false
    - name: Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{steps.version_bump.outputs.tag}}
        release_name: ylem ${{steps.version_bump.outputs.tag}}
        draft: false
        prerelease: false
  pack:
    needs: release
    strategy:
      matrix:
        platform: [
          {os: ubuntu-latest, path: linux-x86_64},
	  {os: raspbian-private, path: linux-arm64},
        ]
    runs-on: ${{matrix.platform.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deps
      run: sh scripts/install_deps.sh
    - name: Ccache
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ matrix.platform }}-cache-${{ hashFiles('CMakeLists.txt') }}
        restore-keys: |
          ${{ matrix.platform }}-cache-
    - name: Build
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
        echo -n "" >prerelease.txt
        mkdir build && cd build
        cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DPROJECT_VERSION=${{needs.release.outputs.tag}} ..
        make -j4 ylem
    - name: Checksum
      run: cd build/solc && sha256sum ylem > ylem.checksum
    - name: Upload checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{needs.release.outputs.url}}
        asset_path: ./build/solc/ylem.checksum
        asset_name: ylem-${{matrix.platform.path}}.checksum
        asset_content_type: application/zip
    - name: Upload assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: ${{needs.release.outputs.url}}
        asset_path: ./build/solc/ylem
        asset_name: ylem-${{matrix.platform.path}}
        asset_content_type: application/zip
