name: ylem pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: sh scripts/install_deps.sh
    - name: Build
      run: |
         mkdir build && cd build
         cmake ..
         make -j4
