name: gocore docker
on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Version
      id: version
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Docker
      run: |
        docker login ghcr.io -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}}
        docker build . -f scripts/Dockerfile -t ghcr.io/core-coin/ylem:${{steps.version_bump.outputs.tag}} -t ghcr.io/core-coin/ylem:latest
        docker push --all-tags ghcr.io/core-coin/ylem
